# Section C – Coding Practice

## Q16. Swap two numbers in three ways

Arithmetic uses addition and subtraction. XOR works with integers. Tuple unpacking is the most Pythonic method because it is short and easy to read.


In [30]:
a = 10
b = 20
a = a + b
b = a - b
a = a - b
print("Arithmetic:", a, b)

a = 10
b = 20
a = a ^ b
b = a ^ b
a = a ^ b
print("XOR:", a, b)

a = 10
b = 20
a, b = b, a
print("Tuple unpacking:", a, b)

Arithmetic: 20 10
XOR: 20 10
Tuple unpacking: 20 10


## Q17. Swiggy Order Calculator

The subtotal is price × quantity. GST is 18% of the subtotal. Delivery is ₹40 when the subtotal is below ₹500; otherwise it is free.

In [31]:
price = float(input("Enter item price: "))
quantity = int(input("Enter quantity: "))

subtotal = price * quantity
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40
else:
    delivery = 0

final_total = subtotal + gst + delivery

print(f"Subtotal:     ₹{subtotal:.2f}")
print(f"GST (18%):    ₹{gst:.2f}")
print(f"Delivery:     ₹{delivery:.2f}")
print("------------------------")
print(f"Total:        ₹{final_total:.2f}")

Enter item price: 150
Enter quantity: 3
Subtotal:     ₹450.00
GST (18%):    ₹81.00
Delivery:     ₹40.00
------------------------
Total:        ₹571.00


## Q18. Temperature Converter

The program converts Celsius to Fahrenheit or Fahrenheit to Celsius. For any other unit, it shows an error message.

In [32]:
temperature = float(input("Enter temperature: "))
unit = input("Enter unit (C or F): ").strip().upper()

if unit == "C":
    converted = (temperature * 9 / 5) + 32
    print(f"{converted:.2f} F")
elif unit == "F":
    converted = (temperature - 32) * 5 / 9
    print(f"{converted:.2f} C")
else:
    print("Invalid unit. Please enter C or F.")

Enter temperature: 0
Enter unit (C or F): c
32.00 F


## Q19. Sum of the digits of a four-digit number

`% 10` gives the last digit, and `// 10` removes the last digit. The program repeats this four times without converting the number to a string.

In [33]:
number = int(input("Enter a four-digit number: "))

if 1000 <= number <= 9999:
    remaining = number
    digit_sum = 0

    for _ in range(4):
        digit_sum += remaining % 10
        remaining //= 10

    print("Sum of digits:", digit_sum)
else:
    print("Please enter a valid four-digit number.")

Enter a four-digit number: 1234
Sum of digits: 10


## Q20. Smart Input Parser

The program first tries to convert the input to an integer. If that fails, it tries a float. If both conversions fail, it keeps the input as a string.

In [34]:
user_input = input("Enter a value: ")

try:
    value = int(user_input)
except ValueError:
    try:
        value = float(user_input)
    except ValueError:
        value = user_input

print("Value:", value)
print("Detected type:", type(value).__name__)

Enter a value: 10
Value: 10
Detected type: int


## Q21. Income Tax Calculator

Tax is calculated one slab at a time. Only the part of income that falls in a slab is charged at that slab's rate. This program uses the FY 2024–25 slabs given in the assignment.

In [35]:
income = float(input("Enter annual income: ₹"))

if income < 0:
    print("Income cannot be negative.")
else:
    slabs = [
        (300000, 700000, 0.05),
        (700000, 1000000, 0.10),
        (1000000, 1200000, 0.15),
        (1200000, 1500000, 0.20),
        (1500000, float("inf"), 0.30)
    ]

    total_tax = 0
    print("Tax on income up to ₹3,00,000: ₹0.00")

    for lower, upper, rate in slabs:
        taxable_amount = max(0, min(income, upper) - lower)
        slab_tax = taxable_amount * rate

        if taxable_amount > 0:
            print(f"Tax at {rate * 100:.0f}% on ₹{taxable_amount:,.2f}: ₹{slab_tax:,.2f}")
            total_tax += slab_tax

    print(f"Total tax: ₹{total_tax:,.2f}")

Enter annual income: ₹800000
Tax on income up to ₹3,00,000: ₹0.00
Tax at 5% on ₹400,000.00: ₹20,000.00
Tax at 10% on ₹100,000.00: ₹10,000.00
Total tax: ₹30,000.00


## Q22. PAN Format Validator

A PAN must contain exactly 10 characters: five uppercase English letters, four digits, and one uppercase English letter. The program checks each part without using regex.

In [36]:
pan = input("Enter PAN: ").strip()

if len(pan) != 10:
    print("Invalid PAN — it must have exactly 10 characters.")
elif not all("A" <= char <= "Z" for char in pan[:5]):
    print("Invalid PAN — the first five characters must be uppercase letters.")
elif not all("0" <= char <= "9" for char in pan[5:9]):
    print("Invalid PAN — characters 6 to 9 must be digits.")
elif not ("A" <= pan[9] <= "Z"):
    print("Invalid PAN — the last character must be an uppercase letter.")
else:
    print("Valid PAN")

Enter PAN: ABCDE1234F
Valid PAN


## Q23. Electricity Bill

Energy charges are calculated slab by slab using the rates in the assignment. A ₹110 fixed charge is added, followed by 6% tax on energy charges plus the fixed charge.

In [37]:
units = float(input("Enter units consumed: "))

if units < 0:
    print("Units cannot be negative.")
else:
    first_50 = min(units, 50) * 4.10
    next_50 = min(max(units - 50, 0), 50) * 5.55
    next_100 = min(max(units - 100, 0), 100) * 7.10
    above_200 = max(units - 200, 0) * 8.15

    energy_charge = first_50 + next_50 + next_100 + above_200
    fixed_charge = 110
    tax = (energy_charge + fixed_charge) * 0.06
    total = energy_charge + fixed_charge + tax

    print(f"0–50 units:       ₹{first_50:.2f}")
    print(f"51–100 units:     ₹{next_50:.2f}")
    print(f"101–200 units:    ₹{next_100:.2f}")
    print(f"Above 200 units:  ₹{above_200:.2f}")
    print(f"Energy charges:   ₹{energy_charge:.2f}")
    print(f"Fixed charge:     ₹{fixed_charge:.2f}")
    print(f"Government tax:   ₹{tax:.2f}")
    print(f"Total bill:       ₹{total:.2f}")

Enter units consumed: 100
0–50 units:       ₹205.00
51–100 units:     ₹277.50
101–200 units:    ₹0.00
Above 200 units:  ₹0.00
Energy charges:   ₹482.50
Fixed charge:     ₹110.00
Government tax:   ₹35.55
Total bill:       ₹628.05


## Q24. Cricket Strike Rate Classifier

Strike rate is runs divided by balls, multiplied by 100. The program checks for zero balls before division and then classifies the result using the assignment's ranges.

In [38]:
runs = int(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if runs < 0 or balls < 0:
    print("Runs and balls cannot be negative.")
elif balls == 0:
    print("Strike rate cannot be calculated when balls faced is 0.")
else:
    strike_rate = (runs / balls) * 100

    if strike_rate > 150:
        category = "Explosive (T20 finisher)"
    elif strike_rate > 100:
        category = "Aggressive (Top order T20)"
    elif strike_rate >= 75:
        category = "Steady (ODI anchor)"
    else:
        category = "Defensive (Test match)"

    print(f"Strike rate: {strike_rate:.2f}")
    print("Category:", category)

Enter runs scored: 60
Enter balls faced: 40
Strike rate: 150.00
Category: Aggressive (Top order T20)


## Q25. BMI Calculator

Height is converted from centimetres to metres. BMI is weight divided by height in metres squared. The category follows the Indian ranges given in the assignment.

In [39]:
weight = float(input("Enter weight in kg: "))
height_cm = float(input("Enter height in cm: "))

if weight <= 0 or height_cm <= 0:
    print("Weight and height must be greater than 0.")
else:
    height_m = height_cm / 100
    bmi = weight / (height_m ** 2)

    if bmi < 18.5:
        category = "Underweight"
    elif bmi < 23:
        category = "Normal"
    elif bmi < 25:
        category = "Overweight"
    elif bmi < 30:
        category = "Obese Class I"
    else:
        category = "Obese Class II"

    print(f"BMI: {bmi:.2f}")
    print("Category:", category)

Enter weight in kg: 60
Enter height in cm: 160
BMI: 23.44
Category: Overweight


## Q26. Increasing number pattern

The outer loop selects the row. The inner loop prints numbers from 1 up to that row number.

In [40]:
n = int(input("Enter N: "))

for row in range(1, n + 1):
    for number in range(1, row + 1):
        print(number, end=" ")
    print()

Enter N: 5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


## Q27. Number diamond

For each row, the numbers rise from 1 to the row number and then fall back to 1. The upper part grows to N, and the lower part shrinks.

In [41]:
n = int(input("Enter N: "))

for row in range(1, n + 1):
    for space in range(n - row):
        print(" ", end=" ")

    for number in range(1, row + 1):
        print(number, end=" ")

    for number in range(row - 1, 0, -1):
        print(number, end=" ")

    print()

for row in range(n - 1, 0, -1):
    for space in range(n - row):
        print(" ", end=" ")

    for number in range(1, row + 1):
        print(number, end=" ")

    for number in range(row - 1, 0, -1):
        print(number, end=" ")

    print()

Enter N: 6
          1 
        1 2 1 
      1 2 3 2 1 
    1 2 3 4 3 2 1 
  1 2 3 4 5 4 3 2 1 
1 2 3 4 5 6 5 4 3 2 1 
  1 2 3 4 5 4 3 2 1 
    1 2 3 4 3 2 1 
      1 2 3 2 1 
        1 2 1 
          1 


## Q28. Hollow square

A star is printed on the first row, last row, first column, and last column. All inner positions are left blank.

In [42]:
n = int(input("Enter N: "))

for row in range(n):
    for column in range(n):
        if row == 0 or row == n - 1 or column == 0 or column == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

Enter N: 4
* * * * 
*     * 
*     * 
* * * * 


## Q29. First five rows of Pascal's Triangle

Each row starts with 1. The next number is calculated from the previous number, so no imported function is needed.

In [43]:
for row in range(5):
    for space in range(4 - row):
        print(" ", end=" ")

    value = 1
    for position in range(row + 1):
        print(value, end="   ")
        value = value * (row - position) // (position + 1)

    print()

        1   
      1   1   
    1   2   1   
  1   3   3   1   
1   4   6   4   1   


## Q30. Increasing letter pattern

`ord("A")` gives the number for the letter A, and `chr()` converts a number back to a letter. The inner loop prints letters up to the current row.

In [44]:
n = int(input("Enter N (1 to 26): "))

if n < 1 or n > 26:
    print("Please enter a number from 1 to 26.")
else:
    for row in range(1, n + 1):
        for position in range(row):
            print(chr(ord("A") + position), end=" ")
        print()

Enter N (1 to 26): 15
A 
A B 
A B C 
A B C D 
A B C D E 
A B C D E F 
A B C D E F G 
A B C D E F G H 
A B C D E F G H I 
A B C D E F G H I J 
A B C D E F G H I J K 
A B C D E F G H I J K L 
A B C D E F G H I J K L M 
A B C D E F G H I J K L M N 
A B C D E F G H I J K L M N O 


## Q31. Armstrong numbers from 1 to 9999

For each number, I count its digits and add each digit raised to that count. If the sum equals the original number, it is an Armstrong number.

In [45]:
armstrong_numbers = []

for number in range(1, 10000):
    digit_count = 0
    remaining = number

    while remaining > 0:
        digit_count += 1
        remaining //= 10

    digit_power_sum = 0
    remaining = number

    while remaining > 0:
        digit = remaining % 10
        digit_power_sum += digit ** digit_count
        remaining //= 10

    if digit_power_sum == number:
        armstrong_numbers.append(number)

print("Armstrong numbers:", end=" ")
print(*armstrong_numbers, sep=", ")
print("Count:", len(armstrong_numbers))

Armstrong numbers: 1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


## Q32. First N Fibonacci terms and their sum

The series starts with 0 and 1. Each new term is the sum of the previous two terms. A loop prints exactly N terms and adds them to the total.

In [46]:
n = int(input("Enter N: "))

if n < 0:
    print("N cannot be negative.")
else:
    first = 0
    second = 1
    total = 0

    print("Fibonacci terms:", end=" ")

    for _ in range(n):
        print(first, end=" ")
        total += first
        first, second = second, first + second

    print()
    print("Sum:", total)

Enter N: 0
Fibonacci terms: 
Sum: 0


## Q33. Prime check and sum of primes

A number is prime if it has no divisor other than 1 and itself. To test it efficiently, I check divisors only while divisor × divisor is less than or equal to the number.

In [47]:
n = int(input("Enter N: "))

if n < 2:
    print(n, "is not prime.")
    print("Sum of primes from 2 to N: 0")
else:
    n_is_prime = True
    divisor = 2

    while divisor * divisor <= n:
        if n % divisor == 0:
            n_is_prime = False
            break
        divisor += 1

    if n_is_prime:
        print(n, "is prime.")
    else:
        print(n, "is not prime.")

    prime_sum = 0

    for number in range(2, n + 1):
        is_prime = True
        divisor = 2

        while divisor * divisor <= number:
            if number % divisor == 0:
                is_prime = False
                break
            divisor += 1

        if is_prime:
            prime_sum += number

    print("Sum of primes from 2 to N:", prime_sum)

Enter N: 5
5 is prime.
Sum of primes from 2 to N: 10


## Q34. Reverse a number without using a string

I take the last digit with `% 10` and build the reversed number with multiplication. A negative number is always reported as not a palindrome.

In [48]:
original = int(input("Enter a number: "))
remaining = abs(original)
reversed_number = 0

while remaining > 0:
    digit = remaining % 10
    reversed_number = reversed_number * 10 + digit
    remaining //= 10

if original < 0:
    reversed_number = -reversed_number

print("Reversed number:", reversed_number)

if original >= 0 and original == reversed_number:
    print("Palindrome")
else:
    print("Not palindrome")

Enter a number: 5
Reversed number: 5
Palindrome


## Q35. HCF and LCM

Euclid's algorithm repeatedly replaces the two numbers with the second number and their remainder. When the second number becomes 0, the first is the HCF. LCM is `(a × b) / HCF`.

In [49]:
a = int(input("Enter first positive integer: "))
b = int(input("Enter second positive integer: "))

if a <= 0 or b <= 0:
    print("Both numbers must be positive.")
else:
    first = a
    second = b

    while second != 0:
        first, second = second, first % second

    hcf = first
    lcm = (a * b) // hcf

    print("HCF:", hcf)
    print("LCM:", lcm)

Enter first positive integer: 12
Enter second positive integer: 18
HCF: 6
LCM: 36


## Q36. String scanner in one pass

The program visits each character only once. It counts words when a non-space character starts a new word, and classifies each character as a letter, digit, space, or special character.

In [50]:
sentence = input("Enter a sentence: ")

characters = 0
words = 0
vowels = 0
consonants = 0
digits = 0
spaces = 0
special_characters = 0
inside_word = False

for character in sentence:
    characters += 1

    if character.isspace():
        if character == " ":
            spaces += 1
        inside_word = False
    else:
        if not inside_word:
            words += 1
            inside_word = True

        if character.lower() in "aeiou":
            vowels += 1
        elif character.isalpha():
            consonants += 1
        elif character.isdigit():
            digits += 1
        else:
            special_characters += 1

print("Total characters:", characters)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", special_characters)

Enter a sentence: HELLO
Total characters: 5
Total words: 1
Vowels: 2
Consonants: 3
Digits: 0
Spaces: 0
Special characters: 0


## Q37. Analyse 10 student marks

I read 10 marks, then use loops to find the maximum, minimum, average, count above average, and second highest distinct mark. I do not use `sort()` or `sorted()`.

In [51]:
marks = list(map(int, input("Enter 10 marks separated by spaces: ").split()))

if len(marks) != 10 or any(mark < 0 or mark > 100 for mark in marks):
    print("Please enter exactly 10 marks between 0 and 100.")
else:
    highest = marks[0]
    lowest = marks[0]
    total = 0

    for mark in marks:
        if mark > highest:
            highest = mark
        if mark < lowest:
            lowest = mark
        total += mark

    average = total / 10
    above_average = 0
    second_highest = None

    for mark in marks:
        if mark > average:
            above_average += 1
        if mark < highest and (second_highest is None or mark > second_highest):
            second_highest = mark

    print("Maximum:", highest)
    print("Minimum:", lowest)
    print(f"Average: {average:.2f}")
    print("Students above average:", above_average)

    if second_highest is None:
        print("Second highest: No distinct second highest mark")
    else:
        print("Second highest:", second_highest)

Enter 10 marks separated by spaces: 10 30 75 40 65 86 60 80 90 95
Maximum: 95
Minimum: 10
Average: 63.10
Students above average: 6
Second highest: 90


## Q38. Word Frequency Analyzer

I convert words to lowercase so “Food” and “food” count as the same word. A dictionary stores the counts, which are then displayed from most frequent to least frequent.

In [65]:
review = input("Enter a review: ")
frequency = {}

for raw_word in review.split():
    word = raw_word.strip(".,!?;:'\"()[]").lower()

    if word:
        if word in frequency:
            frequency[word] += 1
        else:
            frequency[word] = 1

if not frequency:
    print("No words found.")
else:
    remaining_words = list(frequency.keys())
    sorted_words = []

    while remaining_words:
        most_frequent = remaining_words[0]

        for word in remaining_words:
            if frequency[word] > frequency[most_frequent]:
                most_frequent = word
            elif frequency[word] == frequency[most_frequent] and word < most_frequent:
                most_frequent = word

        sorted_words.append(most_frequent)
        remaining_words.remove(most_frequent)

    print("Word frequencies:")
    for word in sorted_words:
        print(word, ":", frequency[word])

    print("Most frequent word:", sorted_words[0])
    print("Count:", frequency[sorted_words[0]])

Enter a review: food was good
Word frequencies:
food : 1
good : 1
was : 1
Most frequent word: food
Count: 1


## Q39. Indian States CRUD

A dictionary stores each state and its capital. The menu repeats until the user chooses Exit, allowing add, update, delete, search, and display operations.

In [54]:
capitals = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Gujarat": "Gandhinagar",
    "Rajasthan": "Jaipur"
}

while True:
    print("\n1. Add a state")
    print("2. Update a capital")
    print("3. Delete a state")
    print("4. Search a state")
    print("5. Display all states")
    print("6. Exit")

    choice = input("Choose an option (1-6): ")

    if choice == "1":
        state = input("State name: ").strip().title()
        if state in capitals:
            print("State already exists.")
        else:
            capital = input("Capital name: ").strip().title()
            capitals[state] = capital
            print("State added.")

    elif choice == "2":
        state = input("State to update: ").strip().title()
        if state in capitals:
            capitals[state] = input("New capital: ").strip().title()
            print("Capital updated.")
        else:
            print("State not found.")

    elif choice == "3":
        state = input("State to delete: ").strip().title()
        if state in capitals:
            del capitals[state]
            print("State deleted.")
        else:
            print("State not found.")

    elif choice == "4":
        state = input("State to search: ").strip().title()
        print(capitals.get(state, "Not found"))

    elif choice == "5":
        for state in sorted(capitals):
            print(state, "→", capitals[state])

    elif choice == "6":
        print("Exiting program.")
        break

    else:
        print("Invalid option. Choose 1 to 6.")


1. Add a state
2. Update a capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Choose an option (1-6): 5
Gujarat → Gandhinagar
Karnataka → Bengaluru
Maharashtra → Mumbai
Rajasthan → Jaipur
Tamil Nadu → Chennai

1. Add a state
2. Update a capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Choose an option (1-6): 4
State to search: Maharashtra
Mumbai

1. Add a state
2. Update a capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Choose an option (1-6): 6
Exiting program.


## Q40. Languages known by Sections A and B

Intersection finds languages both sections know. Difference finds languages unique to one section. Union finds all languages, and symmetric difference finds languages in exactly one section.

In [55]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}

print("Both sections:", section_a & section_b)
print("Only Section A:", section_a - section_b)
print("Only Section B:", section_b - section_a)
print("Total unique languages:", section_a | section_b)
print("Exclusive to one section:", section_a ^ section_b)

Both sections: {'Java', 'SQL', 'Python'}
Only Section A: {'C++'}
Only Section B: {'Go', 'JavaScript'}
Total unique languages: {'Go', 'SQL', 'Java', 'C++', 'JavaScript', 'Python'}
Exclusive to one section: {'Go', 'C++', 'JavaScript'}


## Q41. TCS Stock Price Analysis

I compare the seven prices with their day names. Each day's price is compared with the previous day's price to find the largest gain and the total absolute change.

In [29]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

maximum = max(prices)
minimum = min(prices)
average = sum(prices) / len(prices)

biggest_gain = prices[1] - prices[0]
gain_from = days[0]
gain_to = days[1]
volatility = 0

for index in range(1, len(prices)):
    change = prices[index] - prices[index - 1]
    volatility += abs(change)

    if change > biggest_gain:
        biggest_gain = change
        gain_from = days[index - 1]
        gain_to = days[index]

print("Maximum:", maximum, "on", days[prices.index(maximum)])
print("Minimum:", minimum, "on", days[prices.index(minimum)])
print(f"Average: ₹{average:.2f}")
print("Biggest single-day gain:", biggest_gain, "from", gain_from, "to", gain_to)
print("Total volatility:", volatility)

Maximum: 4055 on Sun
Minimum: 3845 on Mon
Average: ₹3949.29
Biggest single-day gain: 77 from Wed to Thu
Total volatility: 286


## Q42. Numbers with different frequencies

A dictionary counts how often each number appears. I use those counts to make a list of repeated numbers and a separate list of numbers that appear exactly once.


In [56]:
numbers = [4, 7, 2, 4, 9, 1, 7, 5, 3, 2,
           8, 6, 9, 10, 11, 5, 12, 13, 14, 15]

counts = {}

for number in numbers:
    if number in counts:
        counts[number] += 1
    else:
        counts[number] = 1

unique_numbers = set(numbers)
repeated_numbers = []
appearing_once = []

for number in counts:
    if counts[number] > 1:
        repeated_numbers.append(number)
    else:
        appearing_once.append(number)

print("Set of unique numbers:", unique_numbers)
print("Numbers appearing more than once:", repeated_numbers)
print("Numbers appearing exactly once:", appearing_once)

Set of unique numbers: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
Numbers appearing more than once: [4, 7, 2, 9, 5]
Numbers appearing exactly once: [1, 3, 8, 6, 10, 11, 12, 13, 14, 15]


## Q43. Smart Palindrome Checker

I keep only letters and digits, convert them to lowercase, and then compare the cleaned text with its reverse. This ignores spaces, punctuation, and case.

In [57]:
sentence = input("Enter a sentence: ")
cleaned = ""

for character in sentence:
    if character.isalnum():
        cleaned += character.lower()

if cleaned == cleaned[::-1]:
    print("Palindrome")
else:
    print("Not palindrome")

Enter a sentence: a man
Not palindrome


## Q44. Manual Title Case

I read the sentence character by character. The first letter after a space is changed to uppercase, and the other letters are changed to lowercase. I do not use `title()` or `capitalize()`.

In [58]:
sentence = input("Enter a sentence: ")
result = ""
start_of_word = True

for index in range(len(sentence)):
    character = sentence[index]

    if character == " ":
        result += character
        start_of_word = True
    elif start_of_word:
        result += character.upper()
        start_of_word = False
    else:
        result += character.lower()

print("Title case:", result)

Enter a sentence: hello world from Bengaluru
Title case: Hello World From Bengaluru


## Q45. Caesar Cipher Encryptor

Each English letter moves forward by the given shift. `% 26` wraps letters around the alphabet. Uppercase and lowercase are preserved, while spaces, digits, and punctuation stay unchanged.

In [59]:
message = input("Enter a message: ")
shift = int(input("Enter shift value: "))
encrypted = ""

for character in message:
    if "A" <= character <= "Z":
        position = ord(character) - ord("A")
        new_position = (position + shift) % 26
        encrypted += chr(ord("A") + new_position)
    elif "a" <= character <= "z":
        position = ord(character) - ord("a")
        new_position = (position + shift) % 26
        encrypted += chr(ord("a") + new_position)
    else:
        encrypted += character

print("Encrypted message:", encrypted)

Enter a message: hello,India
Enter shift value: 3
Encrypted message: khoor,Lqgld


## Q46. GST Calculator Function

When the amount excludes GST, the function adds tax to the base amount. When it includes GST, the function works backward to find the base amount. It returns base, GST, and total as a tuple.

In [60]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        total_amount = amount
        base_amount = amount / (1 + gst_rate / 100)
        gst_amount = total_amount - base_amount
    else:
        base_amount = amount
        gst_amount = amount * gst_rate / 100
        total_amount = base_amount + gst_amount

    return (
        round(base_amount, 2),
        round(gst_amount, 2),
        round(total_amount, 2)
    )


print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


## Q47. Recursive Power Function

If the exponent is 0, the answer is 1. For a positive exponent, the function multiplies the base by the result for one smaller exponent. For a negative exponent, it returns the reciprocal.

In [61]:
def power(base, exp):
    if exp == 0:
        return 1
    if exp < 0:
        return 1 / power(base, -exp)
    return base * power(base, exp - 1)


print("power(2, 10) =", power(2, 10))
print("power(5, 0) =", power(5, 0))
print("power(3, -2) =", power(3, -2))

power(2, 10) = 1024
power(5, 0) = 1
power(3, -2) = 0.1111111111111111


## Q48. Identity Matrix Manipulations

A 5×5 identity matrix has 1 on its diagonal and 0 elsewhere. Multiplying by 10 changes its diagonal to 10. Its transpose looks the same because the diagonal stays in the same place.

In [62]:
import numpy as np

identity = np.eye(5)
print("Identity matrix:")
print(identity)

multiplied = identity * 10
print("\nAfter multiplying by 10:")
print(multiplied)

# An identity matrix equals its transpose because its diagonal is unchanged.
transposed = multiplied.T
print("\nTranspose:")
print(transposed)

print("\nSum of diagonal elements:", np.trace(transposed))
print("Sum of all elements:", np.sum(transposed))

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After multiplying by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of diagonal elements: 50.0
Sum of all elements: 50.0


## Q49. Zomato Weekly Sales Analytics

NumPy calculates the weekly total, average, maximum day, and growth using array operations. Day-on-day changes compare each day with the previous day without writing a loop.

In [63]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

weekly_total = np.sum(sales)
daily_average = np.mean(sales)
maximum_day = days[np.argmax(sales)]
above_average_days = np.sum(sales > daily_average)
monday_to_sunday_growth = ((sales[-1] - sales[0]) / sales[0]) * 100
daily_changes = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print("Total weekly sales: ₹", weekly_total)
print(f"Daily average: ₹{daily_average:.2f}")
print("Day with maximum sales:", maximum_day)
print("Days above average:", above_average_days)
print(f"Monday to Sunday growth: {monday_to_sunday_growth:.2f}%")
print("Day-on-day percentage changes:", np.round(daily_changes, 2))

Total weekly sales: ₹ 150200
Daily average: ₹21457.14
Day with maximum sales: Sat
Days above average: 3
Monday to Sunday growth: 136.67%
Day-on-day percentage changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


## Q50. Border Pattern without Loops

I start with a 5×5 array of ones. Slicing selects the inner 3×3 area and sets it to zero, leaving ones only on the border.

In [64]:
import numpy as np

border = np.ones((5, 5), dtype=int)
border[1:-1, 1:-1] = 0

print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
